@file:JvmName("Constants")
package app.android.com.musichistory.constants

/**
 * Created by akash
 * on 3/4/18.
 */

const val MUSIC_HISTORY_REALM_FIELD_SONG_ID="songId"
const val MUSIC_HISTORY_REALM_FIELD_SONG_NAME="songName"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_PAUSE = "MUSIC_HISTORY_NOTIFICATION_ACTION_PAUSE"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_NEXT = "MUSIC_HISTORY_NOTIFICATION_ACTION_NEXT"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_PREVIOUS = "MUSIC_HISTORY_NOTIFICATION_ACTION_PREVIOUS"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_PLAY = "MUSIC_HISTORY_NOTIFICATION_ACTION_PLAY"
const val PREFERENCE_KEY_REPEAT_COUNT = "REPEAT_COUNT"
const val MUSIC_HISTORY_SHARED_PREFERENCE = "MUSIC_HISTORY"
const val MUSIC_HISTORY_MUSIC_REPEAT_COUNT_CUSTOM_ACTION="MUSIC_HISTORY_MUSIC_REPEAT_COUNT_CUSTOM_ACTION"
const val MUSIC_HISTORY_SONG_REPEAT_INFINITE = 0
const val MUSIC_HISTORY_SONG_REPEAT_NEVER = -1
const val MUSIC_HISTORY_SONG_REPEAT_ONE_TIME = 1
const val MUSIC_HISTORY_SONG_REPEAT_TWO_TIME=2
const val MUSIC_HISTORY_SONG_REPEAT_THREE_TIME=3
const val MUSIC_HISTORY_MEDIA_SESSION="MusicHistoryMediaSession"
const val MUSIC_HISTORY_NOTIFICATION_ID = 1001
const val MUSIC_HISTORY_LOGGER_STATUS=true