@file:JvmName("Constants")
package app.android.com.musichistory

/**
 * Created by akash
 * on 3/4/18.
 */

const val REALM_FIELD_SONG_ID="songId"
const val REALM_FIELD_SONG_NAME="songName"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_PAUSE = "MUSIC_HISTORY_NOTIFICATION_ACTION_PAUSE"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_NEXT = "MUSIC_HISTORY_NOTIFICATION_ACTION_NEXT"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_PREVIOUS = "MUSIC_HISTORY_NOTIFICATION_ACTION_PREVIOUS"
const val MUSIC_HISTORY_NOTIFICATION_ACTION_PLAY = "MUSIC_HISTORY_NOTIFICATION_ACTION_PLAY"
const val PREFERENCE_KEY_REPEAT_COUNT = "REPEAT_COUNT"
const val SHARED_PREFERENCE_NAME = "MUSIC_HISTORY"
